config/routes.rb
Rails.application.routes.draw do
  resources :rows

  resources :projects do
    member do
      post 'import'
    end
  end

end

app/models/project.rb
require 'json'

class Project < ActiveRecord::Base

  has_many :rows

  def pretty_schema
    if schema.length > 0
      JSON.pretty_generate(JSON.parse(schema))
    else
      "No schema defined."
    end
  end

  def fields
    if schema.length > 0
      JSON.parse(schema)["fields"]
    else
      {}
    end
  end

end

app/models/row.rb
require 'json'

class Row < ActiveRecord::Base

  belongs_to :project

  validates :identifier, uniqueness: { scope: :project_id, message: "repeat identifier seen!" }

  def text
    File.open(identifier, 'r') do |f|
      f.read
    end
  end

  def data_hash
    if data && data.length > 0
      JSON.parse(data)
    else
      {}
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    set_project

    dir_glob_str = "#{Rails.root}/public/data/" + params[:src] + "/*"
    Dir.glob(dir_glob_str).select { |f| File.file?(f) }.each do |filename|
      puts filename
      row = @project.rows.new
      row.identifier = filename
      row.save
    end

    respond_to do |format|
      format.html { redirect_to @project, notice: 'Imported files from ' + params[:src] + '.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :settings, :schema)
    end
end

app/controllers/rows_controller.rb
class RowsController < ApplicationController
  before_action :set_row, only: [:show, :edit, :update, :destroy]

  # GET /rows
  # GET /rows.json
  def index
    @rows = Row.all
  end

  # GET /rows/1
  # GET /rows/1.json
  def show
  end

  # GET /rows/new
  def new
    @row = Row.new
  end

  # GET /rows/1/edit
  def edit
  end

  # POST /rows
  # POST /rows.json
  def create
    @row = Row.new(row_params)

    respond_to do |format|
      if @row.save
        format.html { redirect_to @row, notice: 'Row was successfully created.' }
        format.json { render :show, status: :created, location: @row }
      else
        format.html { render :new }
        format.json { render json: @row.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rows/1
  # PATCH/PUT /rows/1.json
  def update
    respond_to do |format|
      if @row.update(row_params)
        format.html { redirect_to @row, notice: 'Row was successfully updated.' }
        format.json { render :show, status: :ok, location: @row }
      else
        format.html { render :edit }
        format.json { render json: @row.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rows/1
  # DELETE /rows/1.json
  def destroy
    @row.destroy
    respond_to do |format|
      format.html { redirect_to rows_url, notice: 'Row was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_row
      @row = Row.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def row_params
      params.require(:row).permit(:identifier, :project_id, :data)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/rows_helper.rb
module RowsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Labeler</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= projects_path %>">
        Behold! The Labeler!
      </a>
    </div>
  </div>
</nav>

<div style="margin: 15px;">
  <%= yield %>
</div>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :settings %><br>
    <%= f.text_area :settings %>
  </div>
  <div class="field">
    <%= f.label :schema %><br>
    <%= f.text_area :schema %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<ol class="breadcrumb">
  <li class="active">All Projects</li>
</ol>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Settings</th>
      <th>Schema</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, project %></td>
        <td><%= project.description %></td>
        <td><%= project.settings %></td>
        <td><%= project.schema %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<ol class="breadcrumb">
  <li><%= link_to "All", projects_path %></li>
  <li class="active"><%= @project.name %> (<a data-toggle="collapse" href="#schemaCollapse" aria-expanded="false" aria-controls="schemaCollapse">show schema</a>, <%= link_to "edit", edit_project_path(@project)  %>)</li>
</ol>

<p>
  <%= @project.description %>
</p>

<p>
  <%= @project.settings %>
</p>

<div class="collapse" id="schemaCollapse">
<p>
  <pre><%= @project.pretty_schema %></pre>
</p>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Identifier</th>
      <!-- <th>Data</th> -->
      <% fields = @project.fields %>
      <% fields.each do |k, v| %>
        <th><%= v["name"] %></th>
      <% end %>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @project.rows.each do |row| %>
      <tr>
        <td><%= link_to row.identifier, row %></td>
        <!-- <td><%= row.data %></td> -->
        <% dh = row.data_hash %>
        <% fields.each do |k, v| %>
          <td><%= v["options"][dh[k]] %></td>
        <% end %>
        <td><%= link_to 'Edit', edit_row_path(row) %>, <%= link_to 'Delete', row, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr>

<h4>Import from Directory?</h4>

<%= form_tag(import_project_path(@project)) do %>

  <%= text_field_tag(:src) %>

  <%= submit_tag("Import From Directory") %>

<% end %>

app/views/rows/_form.html.erb
<%= form_for(@row) do |f| %>
  <% if @row.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@row.errors.count, "error") %> prohibited this row from being saved:</h2>

      <ul>
      <% @row.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :identifier %><br>
    <%= f.text_field :identifier %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br>
    <%= f.number_field :project_id %>
  </div>
  <div class="field">
    <%= f.label :data %><br>
    <%= f.text_area :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rows/edit.html.erb
<h1>Editing Row</h1>

<%= render 'form' %>

<%= link_to 'Show', @row %> |
<%= link_to 'Back', rows_path %>

app/views/rows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rows</h1>

<table>
  <thead>
    <tr>
      <th>Identifier</th>
      <th>Project</th>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rows.each do |row| %>
      <tr>
        <td><%= row.identifier %></td>
        <td><%= row.project_id %></td>
        <td><%= row.data %></td>
        <td><%= link_to 'Show', row %></td>
        <td><%= link_to 'Edit', edit_row_path(row) %></td>
        <td><%= link_to 'Destroy', row, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Row', new_row_path %>

app/views/rows/new.html.erb
<h1>New Row</h1>

<%= render 'form' %>

<%= link_to 'Back', rows_path %>

app/views/rows/show.html.erb
<p id="notice"><%= notice %></p>

<ol class="breadcrumb">
  <li><%= link_to "All", projects_path %></li>
  <li><%= link_to @row.project.name, @row.project %></li>
  <li class="active"><%= @row.identifier %></li>
</ol>

<div class="row">
  <div class="col-md-7">
    <pre><%= @row.text.encode!('UTF-8', 'UTF-8', :invalid => :replace) %></pre>
  </div>
  <div class="col-md-5">
    <div class="panel panel-default">
      <div class="panel-body">
        <form class="form-inline" id="questionomatic">
          <div class="input-group" style="width: 100%">
            <div class="input-group-addon" style="width: 10%;">Is it</div>
            <input id="question_text" type="text" class="form-control" placeholder="red or blue" autocomplete="off">
            <div class="input-group-addon" style="width: 10%;">?</div>
          </div>
          <!-- <div class="form-group">
            <button id="question_makeitso" class="btn btn-primary">Add Question</button>
          </div> -->
        </form>
        <div id="question_result" style="margin-top: 6px; text-align: center; font-size: larger;">Type something above?</div>
      </div>
    </div>

    <form class="form" id="form_for_schema">
      <ul id="form_for_schema_sortable" style="list-style: none; padding: 0;">

      </ul>
    </form>

    <%= form_for(@row.project, remote: true) do |f| %>
      <%= f.hidden_field :schema, cols: 60, rows: 3 %>
    <% end %>
    <%= form_for(@row, remote: true) do |f| %>
      <%= f.hidden_field :data, cols: 60, rows: 3 %>
    <% end %>

    <%= link_to 'Edit (Debug)', edit_row_path(@row) %>
  </div>
</div>

<div class="modal fade" id="labelChanger" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="labelChangerLabel">Change Name</h4>
      </div>
      <div class="modal-body">
        <form>
          <input type="hidden" value="" id="labelChangerIdentifier" />
          <input class="form-control" type="text" id="labelChangerName" />
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary" id="labelChangerConfirm">Change</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="optionChanger" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="optionChangerLabel">Change Options</h4>
      </div>
      <div class="modal-body">
        <form>
          <input type="hidden" value="" id="optionChangerIdentifier" />
          <div id="optionChangerOptions"></div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary" id="optionChangerConfirm">Change</button>
      </div>
    </div>
  </div>
</div>

<script>

var trimmed_parts = [];
var fields = [];

var schema = { "fields": {}, "order": [] };
var data = {};

function create_multiple_choice(identifier, name, options) {
  var html = "<li data-identifier=\"" + identifier + "\">";
  html += "<div class=\"panel panel-default\"><div class=\"panel-heading\">";
  html += "<a href=\"#\" id=\"label_" + identifier + "\" title=\"" + identifier + "\">" + name + "</a>";
  html += "<div class=\"btn-group btn-group-xs pull-right\" style=\"line-height: 1.5;\"><button type=\"button\" class=\"btn btn-default\" id=\"options_" + identifier + "\">edit options</button></div>";
  html += "</div>";
  html += "<div class=\"panel-body\">"
  html += "<div id=\"buttons_" + identifier + "\" class=\"btn-group\" data-toggle=\"buttons\">\n";
  for (var k in options) {
    html += "<label class=\"btn btn-default\"><input type=\"radio\" autocomplete=\"off\" name=\"" + identifier + "\" value=\"" + k + "\"> <span>" + options[k] + "</span></label>";
  }
  html += "<div id=\"clear_" + identifier + "\" class=\"pull-left\" style=\"padding: 6px 12px; border: 1px solid #ccc; margin-left: -1px; border-radius: 0px 4px 4px 0px; cursor: pointer; font-weight: bold;\">&times;</div></div>";
  html += "</div></div>";
  html += "</li>";
  $("#form_for_schema_sortable").append(html);
  $("#label_" + identifier).click(function() {
    $("#labelChangerIdentifier").val(identifier);
    $("#labelChangerName").val(name);
    $('#labelChanger').modal();
  });
  $("#options_" + identifier).click(function() {
    $("#optionChangerIdentifier").val(identifier);
    $("#optionChangerOptions").html("");
    for (var k in options) {
      $("#optionChangerOptions").append("<input type=\"text\" class=\"form-control\" data-key=\"" + k + "\" value=\"" + options[k] + "\"><br>");
    }
    $("#optionChanger").modal();
  })
  $("#clear_" + identifier).click(function() {
    delete data[identifier];
    $("#form_for_schema input[name=" + identifier + "]").prop("checked", false);
    $("#buttons_" + identifier + " label").removeClass("active");
    update_data();
  });
  fields.push(identifier);
}

function update_schema(identifier, name, options) {
  schema.fields[identifier] = { "name": name, "options": options }
  schema.order.push(identifier);
  $("#project_schema").val(JSON.stringify(schema));
  $("#project_schema").parent().submit();
}

function update_data() {
  for (var i = 0; i < fields.length; i++) {
    var fval = $("#form_for_schema input[name=" + fields[i] + "]:checked").val();
    data[fields[i]] = fval;
  }
  $("#row_data").val(JSON.stringify(data));
  $("#row_data").parent().submit();
}

$(document).ready(function() {

  $("#form_for_schema_sortable").sortable({
    axis: "y",
    start: function( event, ui ) {
      ui.item.css({
        "background-color": "#fcfcfc",
        "margin-left": "",
        "padding-left": "10px",
        "border-left": "10px solid #ccc"
      });
    },
    stop: function( event, ui ) {
      ui.item.css({
        "background-color": "",
        "margin-left": "",
        "padding-right": "",
        "padding-left": "",
        "border-left": ""
      });
    },
    update: function( event, ui ) {
      var order = $("#form_for_schema_sortable li").map(function() {
        return $(this).data("identifier");
      }).get();
      schema.order = order;
      $("#project_schema").val(JSON.stringify(schema));
      $("#project_schema").parent().submit();
    }
  });

  $("#labelChangerConfirm").click(function() {
    var identifier = $("#labelChangerIdentifier").val();
    var name = $("#labelChangerName").val();
    $("#label_" + identifier).html(name);
    schema.fields[identifier].name = name;
    $("#project_schema").val(JSON.stringify(schema));
    $("#project_schema").parent().submit();
    $("#labelChanger").modal('hide');
  });

  $("#optionChangerConfirm").click(function() {
    var identifier = $("#optionChangerIdentifier").val();
    $("#optionChangerOptions input[type=text]").each(function() {
      var k = $(this).data("key");
      var v = $(this).val();
      schema.fields[identifier].options[k] = v;
      $("#buttons_" + identifier + " input[type=radio][value=" + k + "]").next().html(v);
    });
    $("#project_schema").val(JSON.stringify(schema));
    $("#project_schema").parent().submit();
    $("#optionChanger").modal('hide');
  });

  // Create fields from schema
  if ($("#project_schema").val().length > 0) {
    schema = JSON.parse($("#project_schema").val());
  }
  for (var i = 0; i < schema.order.length; i++) {
    var identifier = schema.order[i];
    var name = schema.fields[identifier].name;
    var options = schema.fields[identifier].options;
    create_multiple_choice(identifier, name, options);
  }

  // Populate fields
  if ($("#row_data").val().length > 0) {
    data = JSON.parse($("#row_data").val());
  }
  for (var k in data) {
    $("#form_for_schema input[name=" + k + "][value=\"" + data[k] + "\"]").prop("checked", true).parent().addClass("active");
  }

  // Question-o-matic

  $("#question_text").keyup(function() {
    var text = $("#question_text").val().trim();
    var re = /(is[\s]+it[\s]+|does[\s]+it[\s]+have)?([\w\s-]+)[\?]*/i;
    if ((m = re.exec(text)) != null) {
      var html = "Is it...";
      var parts = m[2].split(/[\s]+or[\s]+/);
      trimmed_parts = [];
      if (parts.length == 1) {
        parts.push("not " + parts[0]);
      }
      for (var i = 0; i < parts.length; i++) {
        if (i > 0) { html += " or "; }
        html += "<span style=\"background-color: #efefef; padding: 4px; border-radius: 4px; margin: 4px;\">" + parts[i].trim() + "</span>";
        trimmed_parts.push(parts[i].trim());
      }
      html += "?";
      $("#question_result").html(html);
    } else {
      $("#question_result").html("Keep typing!");
    }
  });
  $("#questionomatic").submit(function() {
    if (trimmed_parts.length > 0) {
      var identifierCode = 97;
      while (String.fromCharCode(identifierCode) in schema.fields) {
        identifierCode++;
      }
      var identifier = String.fromCharCode(identifierCode);
      var options = {};
      var chari = 97;
      for (var i = 0; i < trimmed_parts.length; i++) {
        options[String.fromCharCode(chari++)] = trimmed_parts[i];
      }    
      create_multiple_choice(identifier, "Untitled", options);
      update_schema(identifier, "Untitled", options);
      trimmed_parts = [];
      $("#question_text").val("");
      $("#question_result").html("Type something in?");
    }
    return false;
  });
  $("#form_for_schema").delegate("input", "change", function() {
    update_data();
  });
});
</script>